name: Auto Deploy Career Web
on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Production Server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          password: ${{ secrets.DEPLOY_PASSWORD }}
          port: 22
          envs: SUDO_PASS
          script: |
            echo "Starting deployment Career Web..."
            export SUDO_PASS="${{ secrets.DEPLOY_PASSWORD }}"
            cd /home/careerWeb/careerWeb
            echo "$SUDO_PASS" | sudo -S git pull origin main
            echo "$SUDO_PASS" | sudo -S docker compose up -d --build
            echo "$SUDO_PASS" | sudo -S docker image prune -f
            echo "Deployment completed!"